#琉璃玩家FRP 开发版
#请从官网配置文件处复制
#并覆盖这里的全部文本
#请注意:
#不要用Windows自带的记事本去编辑frpc.ini
#因为文件编码格式的问题会导致启动闪退
 
[common]
server_addr = 127.0.0.1
server_port = 2333
protocol = websocket
login_fail_exit = false
user = tokenxxxx
token = liulifrp.cn
dns_server = 8.8.8.8